num1 = int(input("Ingrese un numero: "))
num2 = int(input("Ingrese otro numero: "))
print("La suma es: ", num1 + num2)
print("La resta es: ", num1 - num2)
print("La multiplicacion es: ", num1 * num2)
print("La division es: ", num1 / num2)
print("La division entera es: ", num1 // num2)
print("El residuo es: ", num1 % num2)
print("La potencia es: ", num1 ** num2)